export const juzCatalog = [
  { id: 1, name: "Alif Lam Mim", startPage: 1, surahs: "Al-Fatihah, Al-Baqarah" },
  { id: 2, name: "Sayaqool", startPage: 22, surahs: "Al-Baqarah" },
  { id: 3, name: "Tilkal Rusull", startPage: 42, surahs: "Al-Baqarah, Aal-E-Imran" },
  { id: 4, name: "Lan Tanalu", startPage: 62, surahs: "Aal-E-Imran, An-Nisa" },
  { id: 5, name: "Wal Mohsanat", startPage: 82, surahs: "An-Nisa" },
  { id: 6, name: "La Yuhibbullah", startPage: 102, surahs: "An-Nisa, Al-Ma'idah" },
  { id: 7, name: "Wa Iza Samiu", startPage: 122, surahs: "Al-Ma'idah, Al-An'am" },
  { id: 8, name: "Wa Lau Annana", startPage: 142, surahs: "Al-An'am, Al-A'raf" },
  { id: 9, name: "Qalal Malao", startPage: 162, surahs: "Al-A'raf, Al-Anfal" },
  { id: 10, name: "Wa A'lamu", startPage: 182, surahs: "Al-Anfal, At-Tawbah" },
  { id: 11, name: "Yatazeroon", startPage: 202, surahs: "At-Tawbah, Yunus, Hud" },
  { id: 12, name: "Wa Mamin Da'abat", startPage: 222, surahs: "Hud, Yusuf" },
  { id: 13, name: "Wa Ma Ubrioo", startPage: 242, surahs: "Yusuf, Ar-Ra'd, Ibrahim" },
  { id: 14, name: "Rubama", startPage: 262, surahs: "Ibrahim, Al-Hijr, An-Nahl" },
  { id: 15, name: "Subhanallazi", startPage: 282, surahs: "Al-Isra, Al-Kahf" },
  { id: 16, name: "Qala Alam", startPage: 302, surahs: "Al-Kahf, Maryam, Taha" },
  { id: 17, name: "Aqtarabo", startPage: 322, surahs: "Al-Anbiya, Al-Hajj" },
  { id: 18, name: "Qadd Aflaha", startPage: 342, surahs: "Al-Mu'minun, An-Nur, Al-Furqan" },
  { id: 19, name: "Wa Qalallazina", startPage: 362, surahs: "Al-Furqan, Ash-Shu'ara, An-Naml" },
  { id: 20, name: "A'man Khalaqa", startPage: 382, surahs: "An-Naml, Al-Qasas, Al-Ankabut" },
  { id: 21, name: "Utlu Ma Oohi", startPage: 402, surahs: "Al-Ankabut, Ar-Rum, Luqman, As-Sajdah, Al-Ahzab" },
  { id: 22, name: "Wa Manyaqnut", startPage: 422, surahs: "Al-Ahzab, Saba, Fatir, Ya-Sin" },
  { id: 23, name: "Wa Mali", startPage: 442, surahs: "Ya-Sin, As-Saffat, Sad, Az-Zumar" },
  { id: 24, name: "Faman Azlam", startPage: 462, surahs: "Az-Zumar, Ghafir, Fussilat" },
  { id: 25, name: "Elahe Yuruddo", startPage: 482, surahs: "Fussilat, Ash-Shura, Az-Zukhruf, Ad-Dukhan, Al-Jathiyah" },
  { id: 26, name: "Ha'a Meem", startPage: 502, surahs: "Al-Ahqaf to Adh-Dhariyat" },
  { id: 27, name: "Qala Fama Khatbukum", startPage: 522, surahs: "Adh-Dhariyat to Al-Hadid" },
  { id: 28, name: "Qadd Sami Allah", startPage: 542, surahs: "Al-Mujadila to At-Tahrim" },
  { id: 29, name: "Tabarakallazi", startPage: 562, surahs: "Al-Mulk to Al-Mursalat" },
  { id: 30, name: "Amma Yatasa'aloon", startPage: 582, surahs: "An-Naba to An-Nas" },
] as const;
